[build]
command = "npm install && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"

# 1) Proxy API to Render
[[redirects]]
from = "/api/*"
to = "https://gencorp-backend.onrender.com/:splat"
status = 200
force = true

# 2) Single Page App fallback
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
